# Small CPU Runner: 2 vCPU, 4GB RAM
# GitHub workflow usage: runs-on: pytorch-cpu-small

apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: cpu-small
  namespace: arc-runners
spec:
  githubConfigUrl: "https://github.com/pytorch/pytorch"  # Override via kustomize
  githubConfigSecret: github-secret
  
  runnerScaleSetName: pytorch-cpu-small
  minRunners: 0
  maxRunners: 50
  
  runnerGroup: default
  
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: RUNNER_FEATURE_FLAG_EPHEMERAL
              value: "true"
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
      
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 30Gi
                storageClassName: gp3
